-- You can find more wallpapers in ~/.config/hypr/wallpapers/
-- wallpaper {
--   monitor =*
--   path = ~/.config/hypr/wallpapers/fjord_markus_christ_pixabay.jpg
-- }
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'splash = false' has no enclosing section
