-- Full documentation https://wiki.hyprland.org

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/conf/monitor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitor")
-- Source: ~/.config/hypr/conf/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.config/hypr/conf/cursor.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("cursor")
-- Source: ~/.config/hypr/conf/environments.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("environments")
-- Source: ~/.config/hypr/conf/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/conf/general.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("general")
-- Source: ~/.config/hypr/conf/decoration.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("decoration")
-- Source: ~/.config/hypr/conf/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("animations")
-- Source: ~/.config/hypr/conf/layouts.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("layouts")
-- Source: ~/.config/hypr/conf/misc.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("misc")
-- Source: ~/.config/hypr/conf/windowrules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windowrules")
-- Source: ~/.config/hypr/conf/keybinding.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("keybinding")
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
