-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 8

-- TODO: manual review — unknown section 'listener {' on line 15

-- TODO: manual review — unknown section 'listener {' on line 21

-- TODO: manual review — unknown section 'listener {' on line 26

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock", -- avoid starting multiple hyprlock instances.
        -- lock_cmd = playerctl --all-players pause && pidof hyprlock || hyprlock  # pause all system audio and avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session", -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on", -- to avoid having to press a key twice to turn on the display.
    },
    -- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
    --listener {
    --    timeout = 1800                                # 30min
    --    on-timeout = systemctl suspend                # suspend pc
    --}
})

