-- Execute your favorite apps at launch
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Load udiskie for automount external drives

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("~/.config/hypr/scripts/gtk.sh")
    hl.exec_cmd("sleep 2 && hyprdynamicmonitors run --enable-lid-events --disable-power-events")
end)

