# Execute your favorite apps at launch
exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = swayosd-server
exec-once = waypaper --restore

# Load udiskie for automount external drives
exec-once = udiskie

exec-once = ~/.config/hypr/scripts/gtk.sh
exec-once = sleep 2 && hyprdynamicmonitors run --enable-lid-events --disable-power-events
