-- See https://wiki.hyprland.org/Configuring/Variables/ for more

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    decoration = {
        rounding = 0,
        shadow = {
            enabled = true,
            range = 2,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 2,
            passes = 2,
            special = true,
            brightness = 0.60,
            contrast = 0.75,
        },
    },
})

