-- See https://wiki.hyprland.org/Configuring/Variables/ for more

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 3,
        col = {
            active_border = "rgba(30,72,118,1)",
        },
        -- col.active_border = rgb(e68e0d)
        --col.inactive_border = rgb(e68e0d)
        layout = "dwindle",
        resize_on_border = true,
    },
})

