-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        repeat_rate = 30,
        repeat_delay = 600,
        numlock_by_default = true,
        follow_mouse = 0,
        mouse_refocus = true,
        touchpad = {
            natural_scroll = true,
            clickfinger_behavior = 1,
        },
        natural_scroll = true,
        sensitivity = 0,
        accel_profile = "flat",
    },
    misc = {
        mouse_move_focuses_monitor = false,
    },
})

