-- -----------------------------------------------------
-- Key bindings
-- -----------------------------------------------------

-- SUPER KEY
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local osdclient = "swayosd-client --monitor \"$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')\""
local browser = SCRIPTS .. "/browser.sh"
local filemanager = "thunar"
local SCRIPTS = "~/.config/hypr/scripts"
local SETTINGS = "~/.config/hypr/settings"

-- Vim style bindings
-- TODO: manual review — 'unbind = SUPER, h'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, j'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, J'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, k'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, K'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, l'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.
-- TODO: manual review — 'unbind = SUPER, L'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.

-- Applications
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd(SETTINGS .. "/terminal.sh"))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd(browser))
hl.bind("SUPER + SHIFT + ALT + B", hl.dsp.exec_cmd(browser .. " --private"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd(filemanager))
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("spotify"))
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(SCRIPTS .. "/launcher.sh"))
hl.bind("SUPER + CTRL + E", hl.dsp.exec_cmd(SCRIPTS .. "/launcher.sh -m symbols"))

-- Actions
hl.bind("SUPER + CTRL + R", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind("SUPER + CTRL + Q", hl.dsp.exec_cmd(SCRIPTS .. "/wlogout.sh"))
hl.bind("SUPER + CTRL + K", hl.dsp.exec_cmd(SCRIPTS .. "/keybindings.sh"))
hl.bind("SUPER + CTRL + B", hl.dsp.exec_cmd("pkill waybar && hyprctl dispatch exec waybar"))
hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind("SUPER + escape", hl.dsp.exec_cmd(SCRIPTS .. "/menu.sh system"))
hl.bind("SUPER + SHIFT + CTRL + V", hl.dsp.exec_cmd(SCRIPTS .. "/toggle_vpn.sh"))

-- Display
hl.bind("SUPER + SHIFT + mouse_down", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print " .. _2 .. "}') + 0.5}\")"))
hl.bind("SUPER + SHIFT + mouse_up", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor $(awk \"BEGIN {print $(hyprctl getoption cursor:zoom_factor | grep 'float:' | awk '{print " .. _2 .. "}') - 0.5}\")"))
hl.bind("SUPER + SHIFT + Z", hl.dsp.exec_cmd("hyprctl keyword cursor:zoom_factor 1"))
hl.bind("SUPER + BACKSPACE", hl.dsp.exec_cmd("hyprctl dispatch setprop \"address:$(hyprctl activewindow -j | jq -r '.address')\" opaque toggle"))

-- Windows
-- Close Windows
hl.bind("SUPER + W", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("hyprctl activewindow | grep pid | tr -d 'pid:' | xargs kill"))

-- Tiling
hl.bind("SUPER + P", hl.dsp.window.pseudo())
hl.bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen(1))
hl.bind("SUPER + ALT + F", hl.dsp.window.fullscreen(0))

-- Move focus with SUPER + arrow
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))

-- Swap active window with one next to it with SUPER + SHIFT + arrow keys
hl.bind("SUPER + SHIFT + H", hl.dsp.window.swap("l"))
hl.bind("SUPER + SHIFT + J", hl.dsp.window.swap("d"))
hl.bind("SUPER + SHIFT + K", hl.dsp.window.swap("u"))
hl.bind("SUPER + SHIFT + L", hl.dsp.window.swap("r"))

-- Move workspaces to other monitors
-- TODO: manual review on line 69 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + ALT + H", hl.dsp.movecurrentworkspacetomonitor("l"))
-- TODO: manual review on line 70 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + ALT + J", hl.dsp.movecurrentworkspacetomonitor("d"))
-- TODO: manual review on line 71 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + ALT + K", hl.dsp.movecurrentworkspacetomonitor("u"))
-- TODO: manual review on line 72 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + ALT + L", hl.dsp.movecurrentworkspacetomonitor("r"))

-- Resize
hl.bind("SUPER + CTRL + right", hl.dsp.window.resize("100 0"))
hl.bind("SUPER + CTRL + left", hl.dsp.window.resize("-100 0"))
hl.bind("SUPER + CTRL + down", hl.dsp.window.resize("0 100"))
hl.bind("SUPER + CTRL + up", hl.dsp.window.resize("0 -100"))

-- Captures
hl.bind("SUPER + CTRL + 3", hl.dsp.exec_cmd(SCRIPTS .. "/screenshot.sh smart clipboard"))
hl.bind("SUPER + CTRL + 4", hl.dsp.exec_cmd(SCRIPTS .. "/screenshot.sh"))
hl.bind("SUPER + CTRL + 5", hl.dsp.exec_cmd(SCRIPTS .. "/screenshot.sh fullscreen"))
hl.bind("SUPER + CTRL + 6", hl.dsp.exec_cmd(SCRIPTS .. "/screenrecord.sh"))

-- Copy / Paste
hl.bind("SUPER + C", hl.dsp.send_shortcut("CTRL, Insert, "))
hl.bind("SUPER + V", hl.dsp.send_shortcut("SHIFT, Insert, "))
hl.bind("SUPER + X", hl.dsp.send_shortcut("CTRL, X, "))
-- bindd = SUPER CTRL, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard

-- Move workspaces to other monitors
-- TODO: manual review on line 93 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + SHIFT + ALT + LEFT", hl.dsp.movecurrentworkspacetomonitor("l"))
-- TODO: manual review on line 94 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + SHIFT + ALT + RIGHT", hl.dsp.movecurrentworkspacetomonitor("r"))
-- TODO: manual review on line 95 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + SHIFT + ALT + UP", hl.dsp.movecurrentworkspacetomonitor("u"))
-- TODO: manual review on line 96 — no mapping for dispatcher "movecurrentworkspacetomonitor"
-- hl.bind("SUPER + SHIFT + ALT + DOWN", hl.dsp.movecurrentworkspacetomonitor("d"))

-- Switch workspaces with SUPER + [1-9; 0]
hl.bind("SUPER + code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + code:17", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + code:18", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + code:19", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with SUPER + SHIFT + [1-9; 0]
hl.bind("SUPER + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }))
hl.bind("SUPER + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }))
hl.bind("SUPER + SHIFT + code:19", hl.dsp.window.move({ workspace = 10 }))

-- Move active window silently to a workspace with SUPER + SHIFT + ALT + [1-9; 0]
hl.bind("SUPER + SHIFT + ALT + code:10", hl.dsp.window.move({ workspace = 1, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:11", hl.dsp.window.move({ workspace = 2, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:12", hl.dsp.window.move({ workspace = 3, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:13", hl.dsp.window.move({ workspace = 4, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:14", hl.dsp.window.move({ workspace = 5, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:15", hl.dsp.window.move({ workspace = 6, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:16", hl.dsp.window.move({ workspace = 7, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:17", hl.dsp.window.move({ workspace = 8, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:18", hl.dsp.window.move({ workspace = 9, silent = true }))
hl.bind("SUPER + SHIFT + ALT + code:19", hl.dsp.window.move({ workspace = 10, silent = true }))

-- Control scratchpad
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("scratchpad"))
hl.bind("SUPER + ALT + S", hl.dsp.window.move({ workspace = "special:scratchpad", silent = true }))

-- Laptop multimedia keys for volume and LCD brightness (with OSD)
-- TODO: manual review on line 139 — no mapping for dispatcher "Volume up"
-- hl.bind("XF86AudioRaiseVolume", hl.dsp.Volume_up("exec", osdclient .. " --output-volume raise"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 140 — no mapping for dispatcher "Volume down"
-- hl.bind("XF86AudioLowerVolume", hl.dsp.Volume_down("exec", osdclient .. " --output-volume lower"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 141 — no mapping for dispatcher "Mute"
-- hl.bind("XF86AudioMute", hl.dsp.Mute("exec", osdclient .. " --output-volume mute-toggle"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 142 — no mapping for dispatcher "Mute microphone"
-- hl.bind("XF86AudioMicMute", hl.dsp.Mute_microphone("exec", osdclient .. " --input-volume mute-toggle"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 143 — no mapping for dispatcher "Brightness up"
-- hl.bind("XF86MonBrightnessUp", hl.dsp.Brightness_up("exec", SCRIPTS .. "/brightness.sh +5%"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 144 — no mapping for dispatcher "Brightness down"
-- hl.bind("XF86MonBrightnessDown", hl.dsp.Brightness_down("exec", SCRIPTS .. "/brightness.sh 5%-"), { locked = true, repeating = true, drag = true })
-- bindeld = ,XF86KbdBrightnessUp, Keyboard brightness up, exec, omarchy-brightness-keyboard up
-- bindeld = ,XF86KbdBrightnessDown, Keyboard brightness down, exec, omarchy-brightness-keyboard down
-- bindld = ,XF86KbdLightOnOff, Keyboard backlight cycle, exec, omarchy-brightness-keyboard cycle

-- Precise 1% multimedia adjustments with Alt modifier
-- TODO: manual review on line 150 — no mapping for dispatcher "Volume up precise"
-- hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.Volume_up_precise("exec", osdclient .. " --output-volume +1"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 151 — no mapping for dispatcher "Volume down precise"
-- hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.Volume_down_precise("exec", osdclient .. " --output-volume -1"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 152 — no mapping for dispatcher "Brightness up precise"
-- hl.bind("ALT + XF86MonBrightnessUp", hl.dsp.Brightness_up_precise("exec", SCRIPTS .. "/brightness.sh +1%"), { locked = true, repeating = true, drag = true })
-- TODO: manual review on line 153 — no mapping for dispatcher "Brightness down precise"
-- hl.bind("ALT + XF86MonBrightnessDown", hl.dsp.Brightness_down_precise("exec", SCRIPTS .. "/brightness.sh 1%-"), { locked = true, repeating = true, drag = true })

-- Requires playerctl
-- TODO: manual review on line 156 — no mapping for dispatcher "Next track"
-- hl.bind("XF86AudioNext", hl.dsp.Next_track("exec", osdclient .. " --playerctl next"), { locked = true, drag = true })
-- TODO: manual review on line 157 — no mapping for dispatcher "Pause"
-- hl.bind("XF86AudioPause", hl.dsp.Pause("exec", osdclient .. " --playerctl play-pause"), { locked = true, drag = true })
-- TODO: manual review on line 158 — no mapping for dispatcher "Play"
-- hl.bind("XF86AudioPlay", hl.dsp.Play("exec", osdclient .. " --playerctl play-pause"), { locked = true, drag = true })
-- TODO: manual review on line 159 — no mapping for dispatcher "Previous track"
-- hl.bind("XF86AudioPrev", hl.dsp.Previous_track("exec", osdclient .. " --playerctl previous"), { locked = true, drag = true })

-- Move/resize windows with mainMod + LMB/RMB and dragging
-- TODO: manual review on line 162 — no mapping for dispatcher "Move window"
-- hl.bind("SUPER + mouse:272", hl.dsp.Move_window("movewindow"), { drag = true })
-- TODO: manual review on line 163 — no mapping for dispatcher "Resize window"
-- hl.bind("SUPER + mouse:273", hl.dsp.Resize_window("resizewindow"), { drag = true })

-- Switch audio output with Super + Mute
-- bindld = SUPER, XF86AudioMute, Switch audio output, exec, omarchy-cmd-audio-switch
