-- See https://wiki.hyprland.org/Configuring/Variables/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vfr = true,
    },
})

