-- See https://wiki.hyprland.org/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

