-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- Hyprland 0.53+ syntax
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Tag all windows for default opacity (apps can override with -default-opacity tag)
hl.window_rule({
    match = {
        class = ".*",
    },
    tag = "+default-opacity",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    match = {
        class = "^$",
        title = "^$",
        xwayland = 1,
        float = 1,
        fullscreen = 0,
        pin = 0,
    },
    -- TODO: manual review — unmapped window rule action: "no_focus on"
})

-- App-specific tweaks (may remove default-opacity tag)
-- Bitwarden
hl.window_rule({
    match = {
        class = "^(Bitwarden)$",
    },
    -- TODO: manual review — unmapped window rule action: "no_screen_share on"
    tag = "+floating-window",
})

-- Bitwarden Chrome Extension
-- replace with Firefox / Zen
-- windowrule = no_screen_share on, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default
-- windowrule = tag +floating-window, match:class chrome-nngceckbapebfimnlniiiahkandclblb-Default

-- Browser types
hl.window_rule({
    match = {
        class = "((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium)",
    },
    tag = "+chromium-based-browser",
})

hl.window_rule({
    match = {
        class = "([fF]irefox|zen|librewolf|floorp)",
    },
    tag = "+firefox-based-browser",
})

hl.window_rule({
    match = {
        tag = "chromium-based-browser",
    },
    tag = "-default-opacity",
})

hl.window_rule({
    match = {
        tag = "firefox-based-browser",
    },
    tag = "-default-opacity",
})

-- Only a subtle opacity change, but not for video sites
hl.window_rule({
    match = {
        tag = "firefox-based-browser",
    },
    opacity = "1.0 0.97",
})

-- Floating windows
hl.window_rule({
    match = {
        tag = "floating-window",
    },
    float = true,
    center = true,
    size = "875 600",
})

hl.window_rule({
    match = {
        title = "(bluetuith|gazelle|wiremix|btop|evince|satty|imv|mpv|thunar|ZapZap)",
    },
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "(Alacritty|kitty|com.mitchellh.ghostty|qimgv|Spotify)",
    },
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|thunar)",
        title = "^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files|.*wants to [open|save].*|[C|c]hoose.*)",
    },
    tag = "+floating-window",
})

hl.window_rule({
    match = {
        class = "org.gnome.Calculator",
    },
    float = true,
})

-- Fullscreen screensaver
-- windowrule = fullscreen on, match:class org.omarchy.screensaver
-- windowrule = float on, match:class org.omarchy.screensaver
-- windowrule = animation slide, match:class org.omarchy.screensaver

-- No transparency on media windows
hl.window_rule({
    match = {
        class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv)$",
    },
    tag = "-default-opacity",
    opacity = "1 1",
})

-- Popped window rounding
hl.window_rule({
    match = {
        tag = "pop",
    },
    rounding = 8,
})

-- Prevent idle while open
hl.window_rule({
    match = {
        tag = "noidle",
    },
    -- TODO: manual review — unmapped window rule action: "idle_inhibit always"
})

-- Define terminal tag to style them uniformly
hl.window_rule({
    match = {
        class = "(Alacritty|kitty|com.mitchellh.ghostty)",
    },
    tag = "+terminal",
})

hl.window_rule({
    match = {
        tag = "terminal",
    },
    tag = "-default-opacity",
})

-- windowrule = size 1575 1000, match:tag floating-window
hl.window_rule({
    match = {
        tag = "terminal",
    },
    opacity = "0.8 0.87",
})

-- Apply default opacity after apps have had a chance to opt out
hl.window_rule({
    match = {
        tag = "default-opacity",
    },
    opacity = "0.97 0.9",
})

