## My overrides so that my shit is my shit ##
$terminal = ghostty
$browser = firefox

## Keybinds ##
bindd = SUPER CTRL, 3, Screenshot fullscreen to clipboard, exec, omarchy-cmd-screenshot smart clipboard
bindd = SUPER CTRL, 4, Screenshot area with editing, exec, omarchy-cmd-screenshot
bindd = SUPER CTRL, 5, Screenshot fullscreen to file, exec, omarchy-cmd-screenshot smart

# Vim style bindings
unbind = SUPER, h
unbind = SUPER, j
unbind = SUPER, J
unbind = SUPER, k
unbind = SUPER, K
unbind = SUPER, l
unbind = SUPER, L

# Move focus with SUPER + arrow keys
bindd = SUPER, H, Move window focus left, movefocus, l
bindd = SUPER, J, Move window focus up, movefocus, d
bindd = SUPER, K, Move window focus down, movefocus, u
bindd = SUPER, L, Move window focus right, movefocus, r

# Move workspaces to other monitors
bindd = SUPER ALT, H, Move workspace to left monitor, movecurrentworkspacetomonitor, l
bindd = SUPER ALT, J, Move workspace to up monitor, movecurrentworkspacetomonitor, d
bindd = SUPER ALT, K, Move workspace to down monitor, movecurrentworkspacetomonitor, u
bindd = SUPER ALT, L, Move workspace to right monitor, movecurrentworkspacetomonitor, r

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, J, Swap window up, swapwindow, d
bindd = SUPER SHIFT, K, Swap window down, swapwindow, u
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r

# Keybind menu
bindd = SUPER CTRL, K, Show key bindings, exec, omarchy-menu-keybindings

## Input changes ##
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }

  follow_mouse = 0
  natural_scroll = true
}

decoration {
    active_opacity = 0.8
    inactive_opacity = 0.8
    dim_inactive = false
  }

exec-once = hyprdynamicmonitors run --enable-lid-events --disable-power-events
